# finally block
try:
    print(0/10)
except:
    print("An exception occurred")  
finally:
    print("The 'try except' is finished")  


    # def get_access():
#  try:
#     name = input("Enter your name: ")
#     age = int(input("Enter your age: "))
        
#     if age <= 17:
#                 print(f"{name},You are not allowed to go in !!")
#     else:
#                 print(f"{name},You are allowed to go in !!")
#  except ValueError:
#        print("Umekosea jaribu tena")

# get_access() 
